version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    build:
      context: docker/
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8080:15672"
      - "1885:15675"
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server\""
    env_file:
      - config/login.env
    volumes:
      - type: bind
        source: ./config/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./config/advanced.config
        target: /etc/rabbitmq/advanced.config
        read_only: true
    networks:
      brokernet:
        ipv4_address: 172.16.238.101

networks:
  brokernet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24