version: '3.8'
services:
  bus:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - '15672:15672'
      - '5672:5672'